<?php

namespace Eship\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BusinessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessRepository extends EntityRepository
{
    public function getBusinessList()
    {
        $conn = $this->getEntityManager()
            ->getConnection();

        $sql = '
            SELECT DISTINCT b.business_id, b.name, b.logo, o.firstName, o.lastName, o.initial, b.isActive
            FROM business b NATURAL JOIN owner o
            ORDER BY b.name ASC';
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }

    public function getInactiveBusinessList()
    {
        $conn = $this->getEntityManager()
            ->getConnection();

        $sql = '
            SELECT DISTINCT b.business_id, b.name, b.logo, o.firstName, o.lastName, o.initial
            FROM business b NATURAL JOIN owner o 
            WHERE b.isActive = 0
            ORDER BY b.name ASC';
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }

    public function getBusinessByOwnerId($id)
    {
        return $this->createQueryBuilder('b')
            ->andWhere('b.owner = :idParam')
            ->leftJoin('b.owner', 'o')
            ->addSelect('b.business_id', 'b.name','o.firstName', 'o.lastName', 'o.initial', 'b.logo', 'b.isActive')
            ->setParameter('idParam', $id)
            ->getQuery()
            ->execute();
    }

    public function getBusinessById($business_id)
    {
        return $this->createQueryBuilder('b')
            ->andWhere('b.business_id = :idParam')
            ->leftJoin('b.owner', 'o')
            ->addSelect('b.business_id', 'b.name','o.firstName', 'o.lastName', 'o.initial', 'o.ownerEmail',
                        'b.businessLink', 'b.stageOfDevelopment','b.description', 'b.requestedHelp',
                        'b.numberOfEmployees', 'b.website', 'b.facebook','b.twitter', 'b.logo', 'b.isProject',
                        'b.isActive', 'b.publicInvestment', 'b.privateInvestment','b.participationBusinessCompetition',
                        'b.nameCompetition', 'b.award', 'b.typeOfBusiness', 'b.workedHours', 'b.date')
            ->setParameter('idParam', $business_id)
            ->getQuery()
            ->execute();
    }

    public function getBusinessStatistics($business_id)
    {
        return $this->createQueryBuilder('b')
            ->andWhere('b.business_id = :idParam')
            ->leftJoin('b.meetingReport', 'meetingReport')
            ->addSelect('b.name', 'b.business_id', 'b.stageOfDevelopment', 'b.numberOfEmployees',
                'b.publicInvestment', 'b.privateInvestment', 'b.workedHours', 'COUNT(meetingReport.reportId)
                as numberOfMeetings')
            ->setParameter('idParam', $business_id)
            ->getQuery()
            ->execute();
    }

    public function getGeneralBusinessStatistics()
    {
        return $this->createQueryBuilder('b')
            ->addSelect('SUM(b.numberOfEmployees) as jobsCreated', 'SUM(b.publicInvestment) as totalPublicInvestment',
                'SUM(b.privateInvestment) as totalPrivateInvestment', 'SUM(b.workedHours) as totalWorkedHours')
            ->getQuery()
            ->execute();
    }

    public function countBusiness()
    {
        return $this->createQueryBuilder('b')
            ->select('COUNT(b.business_id) as totalBusiness', 'b.workedHours as worked_hours')
            ->getQuery()
            ->execute();
    }

    public function countNewBusinessInInterval($start, $end)
    {
        return $this->createQueryBuilder('b')
            ->select('COUNT(b.business_id) as newBusinesses', 'b.workedHours as worked_hours')
            ->where('b.date BETWEEN :start AND :end' )
            ->setParameter('start', $start)
            ->setParameter('end', $end)
            ->getQuery()
            ->execute();
    }

}
