<?php

namespace Eship\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function getClient($id)
    {
        return $this->createQueryBuilder('client')
            ->leftJoin('client.owner', 'owner')
            ->andWhere('client.clientId = :idParam')
            ->addSelect('client.clientId', 'client.clientEmail', 'owner.firstName', 'owner.lastName',
                        'owner.initial', 'client.age', 'client.gender', 'client.phone', 'client.relationshipWithUPRM',
                        'client.specification', 'client.department', 'client.businessNotCNDE', 'client.learnOfServices',
                        'client.address1', 'client.address2', 'client.city', 'client.zipCode', 'client.country')
            ->setParameter('idParam', $id)
            ->getQuery()
            ->execute();
    }
}
