<?php
/**
 * Created by PhpStorm.
 * User: Francisco
 * Date: 5/15/2017
 * Time: 11:12 PM
 */

namespace Eship\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * OwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CounselorRequestRepository extends EntityRepository
{

}