<?php
/**
 * Created by PhpStorm.
 * User: Francisco
 * Date: 5/12/2017
 * Time: 1:52 AM
 */
namespace Eship\EventBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * OwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OwnerRepository extends EntityRepository
{
}
