<?php

namespace Eship\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PerformanceReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerformanceReviewRepository extends EntityRepository
{
    public function getPerformanceReviewSummary()
    {
        return $this->createQueryBuilder('pr')
            ->leftJoin('pr.counselor', 'counselor')
            ->addSelect('pr.performanceReviewId', 'pr.date', 'pr.clientEmail', 'pr.clientFirstName', 'pr.clientLastName',
                'pr.satisfactionLevel', 'pr.comment', 'pr.usefulnessOfService', 'pr.city', 'pr.phone','counselor.firstName',
                'counselor.initial', 'counselor.lastName')
            ->addOrderBy('pr.date')
            ->getQuery()
            ->execute();
    }

}
